name: LocalStack Terraform Integration Test

on:
  push:
    branches:
      - Dadrion

  workflow_dispatch: {}

jobs:
  localstack-terraform-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and Start LocalStack Container
        run: |
          run: docker-compose -f order_app/docker-compose.yml up -d

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Run Terraform Init and Validation
        run: |
          terraform init
          terraform validate
          terraform fmt --recursive --check
          terraform plan
          terraform show

      - name: Run Terraform Test
        run: |
          terraform test

      - name: Stop and Delete LocalStack Container
        if: always()
        run: docker compose down
