name: Test Terraform Infrastructure

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-infra:
    name: Apply Code Changes
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Check Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Validate Terraform Code
        id: validate
        run: terraform validate

      - name: Plan Terraform Changes
        id: plan
        run: terraform plan
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
