name: terraform-infra

on:
  push:
    branches:
      - main
      - dev
    paths:
      - order_app/**
  pull_request:
    branches:
      - main
    paths:
      - order_app/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
  terraform-infra:
    name: Apply Terraform Code Changes
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: order_app
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Update to the latest version as needed

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Check Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Validate Terraform Code
        id: validate
        run: terraform validate

      - name: Plan Terraform Changes
        id: plan
        run: terraform plan -lock=false
#attempt to push
